version: "3.7"

services:
  adguard:
    image: adguard/adguardhome
    container_name: adguard
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "53:53"
      - "67:67/udp"
      - "68:68"
      - "40100:80/tcp"
      - "44101:443"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "5443:5443"
    volumes:
      - ${DOCKERDIR}/adguard/work:/opt/adguardhome/work
      - ${DOCKERDIR}/adguard/conf:/opt/adguardhome/conf
    restart: unless-stopped
    networks:
      macvlan_network:
        ipv4_address: 192.168.1.1

networks:
  macvlan_network:
    external: true
    name: macvlan_network
