version: "3.7"

services:
  watchtower:
    container_name: watchtower
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "40080:80"
      - "40081:81"
      - "40443:443"
    volumes:
      - ${DOCKERDIR}/nginx-proxy-manager:/data
      - ${DOCKERDIR}/shared:/shared
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERDIR}/ddclient:/config
    restart: unless-stopped

  organizr:
    image: organizr/organizr
    container_name: organizr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "9983:80"
    volumes:
      - ${DOCKERDIR}/organizr:/config
    restart: unless-stopped

  adguard:
    image: adguard/adguardhome
    container_name: adguard
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    ports:
      - "53:53"
      - "67:67/udp"
      - "68:68"
      - "40100:80/tcp"
      - "44101:443"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "5443:5443"
    volumes:
      - ${DOCKERDIR}/adguard/work:/opt/adguardhome/work
      - ${DOCKERDIR}/adguard/conf:/opt/adguardhome/conf
    restart: unless-stopped
