version: "3.7"

services:
  watchtower:
    container_name: watchtower
    restart: always
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup

  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "40080:80"
      - "40081:81"
      - "40443:443"
    volumes:
      - ${DOCKERDIR}/nginx-proxy-manager:/data
      - ${DOCKERDIR}/shared:/shared
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${DOCKERDIR}/ddclient:/config
    restart: unless-stopped
