version: "3.8"

services:
  plexms:
    container_name: plexms
    network_mode: host
    restart: unless-stopped
    image: plexinc/pms-docker
    volumes:
      - ${DOCKERDIR}/plexms:/config
      - ${USERDIR}/Downloads/plex_tmp:/transcode
      - ${MEDIADIR}:/media
      - ${DOCKERDIR}/shared:/shared
    environment:
      - TZ=${TZ}
      - HOSTNAME=${HOSTNAME}
      - PLEX_CLAIM=${PLEXCLAIM}
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}

  nzbget:
    image: "lscr.io/linuxserver/nzbget"
    container_name: "nzbget"
    volumes:
      - ${DOCKERDIR}/nzbget:/config
      - ${USERDIR}/Downloads:/downloads
      - ${DOCKERDIR}/shared:/shared
    ports:
      - "6789:6789"
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  nzbhydra2:
    image: "lscr.io/linuxserver/nzbhydra2"
    container_name: "nzbhydra2"
    volumes:
      - ${DOCKERDIR}/hydra:/config
      - ${USERDIR}/Downloads:/downloads
      - ${DOCKERDIR}/shared:/shared
    ports:
      - "5076:5076"
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  radarr:
    image: "lscr.io/linuxserver/radarr"
    container_name: "radarr"
    volumes:
      - ${DOCKERDIR}/radarr:/config
      - ${USERDIR}/Downloads:/downloads
      - ${MEDIADIR}/Movies:/movies
      - ${DOCKERDIR}/shared:/shared
    ports:
      - "7878:7878"
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  sonarr:
    image: "lscr.io/linuxserver/sonarr"
    container_name: "sonarr"
    volumes:
      - ${DOCKERDIR}/sonarr:/config
      - ${USERDIR}/Downloads:/downloads
      - ${MEDIADIR}/TV:/tv
      - ${DOCKERDIR}/shared:/shared
    ports:
      - "8989:8989"
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  jackett:
    image: "lscr.io/linuxserver/jackett"
    container_name: "jackett"
    volumes:
      - ${DOCKERDIR}/jackett:/config
      - ${USERDIR}/Downloads:/downloads
      - ${DOCKERDIR}/shared:/shared
    ports:
      - "9117:9117"
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  qbittorrent:
    image: "lscr.io/linuxserver/qbittorrent"
    container_name: "qbittorrent"
    volumes:
      - ${DOCKERDIR}/qbittorrent:/config
      - ${USERDIR}/Downloads:/downloads
      - ${DOCKERDIR}/shared:/shared
    ports:
      - "8080:8080"
      - "6881:6881"
      - "6881:6881/udp"
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - UMASK_SET=002
      - WEBUI_PORT=8080

  calibre-web:
    image: "lscr.io/linuxserver/calibre-web"
    container_name: "calibre-web"
    volumes:
      - ${DOCKERDIR}/calibre-web:/config
      - ${MEDIADIR}/Calibre:/books
      - ${DOCKERDIR}/shared:/shared
    ports:
      - "8083:8083"
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  jdownloader-2:
    image: "jlesage/jdownloader-2"
    container_name: "jdownloader-2"
    volumes:
      - ${DOCKERDIR}/jdownloader-2:/config
      - ${USERDIR}/Downloads:/output
      - ${DOCKERDIR}/shared:/shared
    ports:
      - "5800:5800"
    restart: unless-stopped
    environment:
      - USER_ID=${PUID}
      - GROUP_ID=${PGID}
      - TZ=${TZ}

  readarr:
    image: "lscr.io/linuxserver/readarr:develop"
    container_name: "readarr"
    volumes:
      - ${DOCKERDIR}/readarr:/config
      - ${USERDIR}/Downloads:/downloads
      - ${MEDIADIR}/Calibre:/books
      - ${DOCKERDIR}/shared:/shared
    ports:
      - "8787:8787"
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}

  tautulli:
    image: "lscr.io/linuxserver/tautulli"
    container_name: "tautulli"
    volumes:
      - ${DOCKERDIR}/tautulli:/config
    ports:
      - "8181:8181"
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
